const { chromium } = require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES ? process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES + '/playwright' : 'playwright');
const assert = require('node:assert/strict');
(async () => {
  const browser = await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH,args:['--no-sandbox']});
  const page = await browser.newPage({viewport:{width:393,height:852},timezoneId:'Asia/Shanghai'});
  page.setDefaultTimeout(10000);
  await page.goto(process.env.TEST_URL || 'http://127.0.0.1:3000');
  const padding=await page.locator('#root').evaluate(el=>getComputedStyle(el).padding);
  assert.equal(padding,'0px','手机根布局必须无模板留白');
  const yesterday = await page.evaluate(()=>{const d=new Date();d.setDate(d.getDate()-1);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`});
  await page.evaluate(date=>{localStorage.clear();localStorage.setItem('ledger.expenses.v1', JSON.stringify([{id:'past-1',amount:12,category:'餐饮',date,note:'昨天午饭',createdAt:1}]));},yesterday);
  await page.reload();
  await page.getByRole('button',{name:'昨天',exact:true}).click();
  await page.getByRole('button',{name:'编辑账单',exact:true}).click();
  await page.getByLabel('金额（元）').fill('18.50');
  await page.getByLabel('备注',{exact:true}).fill('修改后的午饭');
  await page.getByRole('button',{name:'保存修改',exact:true}).click();
  await page.reload();
  await page.getByRole('button',{name:'昨天',exact:true}).click();
  assert.equal(await page.getByText('修改后的午饭',{exact:true}).count(),1);
  assert.equal(await page.getByText('-¥18.50',{exact:true}).count(),1);
  await page.getByRole('button',{name:'2',exact:true}).click();
  await page.getByRole('button',{name:'占比',exact:true}).click();
  await page.getByRole('button',{name:'记账',exact:true}).click();
  assert.equal(await page.getByTestId('entry-amount').innerText(),'2');
  for(const width of [320,393,430,768]) {
    await page.setViewportSize({width,height:852});
    assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`horizontal overflow at ${width}`);
  }
  await page.setViewportSize({width:393,height:852});
  await page.getByRole('button',{name:'数据管理',exact:true}).click();
  const [download]=await Promise.all([page.waitForEvent('download'), page.getByRole('button',{name:'导出 JSON',exact:true}).click()]);
  const fs=require('node:fs'); const exported=JSON.parse(fs.readFileSync(await download.path(),'utf8'));
  assert.equal(exported.expenses[0].amount,18.5);
  const input=page.locator('input[type=file]');
  await input.setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{oops')});
  await page.getByText(/无法解析/).waitFor();
  await input.setInputFiles({name:'backup.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(exported))});
  await page.getByRole('button',{name:'取消导入',exact:true}).click();
  await input.setInputFiles({name:'backup.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(exported))});
  await page.getByRole('button',{name:'确认覆盖导入',exact:true}).click();
  await page.getByText('导入成功', {exact:false}).waitFor();
  // A failed second selection must discard the first file's confirmation.
  await input.setInputFiles({name:'backup.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(exported))});
  await page.getByRole('button',{name:'确认覆盖导入',exact:true}).waitFor();
  await input.setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{bad')});
  await page.getByText(/无法解析/).waitFor();
  assert.equal(await page.getByRole('button',{name:'确认覆盖导入',exact:true}).count(),0);
  // Recovery changes the current data and is retained across reload.
  const empty={...exported,expenses:[],budgets:{}};
  await input.setInputFiles({name:'empty.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(empty))});
  await page.getByRole('button',{name:'确认覆盖导入',exact:true}).click();
  await page.getByRole('button',{name:'恢复导入前数据',exact:true}).click();
  await page.getByRole('button',{name:'确认恢复',exact:true}).click();
  assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('ledger.snapshot.v2')).expenses.length),1);
  // Corrupt primary data: valid import unlocks storage and retains original bytes.
  await page.evaluate(()=>localStorage.setItem('ledger.snapshot.v2','{corrupt-original'));
  await page.reload();
  await page.getByRole('button',{name:'数据管理',exact:true}).click();
  await page.getByRole('button',{name:'导出原始数据',exact:true}).waitFor();
  await page.locator('input[type=file]').setInputFiles({name:'backup.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(exported))});
  await page.getByRole('button',{name:'确认覆盖导入',exact:true}).click();
  const snapshot=await page.evaluate(()=>JSON.parse(localStorage.getItem('ledger.snapshot.v2')));
  assert.equal(snapshot.expenses[0].amount,18.5);
  assert.equal(snapshot.unreadableBackup['ledger.snapshot.v2'],'{corrupt-original');
  await page.getByRole('button',{name:'昨天',exact:true}).click();
  await page.getByRole('button',{name:'编辑账单',exact:true}).click();
  await page.getByLabel('分类',{exact:true}).selectOption('交通');
  const today=await page.locator('input[aria-label="记账日期"]').inputValue();
  await page.getByLabel('日期',{exact:true}).fill(today);
  await page.getByRole('button',{name:'保存修改',exact:true}).click();
  await page.getByRole('button',{name:'今天',exact:true}).click();
  await page.getByRole('button',{name:'编辑账单',exact:true}).waitFor();
  await page.getByRole('button',{name:'占比',exact:true}).click();
  await page.getByRole('region',{name:'占比页面',exact:true}).getByText('¥18.50',{exact:true}).first().waitFor();
  await page.getByRole('button',{name:'记账',exact:true}).click();
  await page.getByRole('button',{name:'数据管理',exact:true}).click();
  await page.locator('.tab-page:not([hidden])').evaluate(el=>el.scrollTop=0);
  await page.screenshot({path:'../deliverables/mobile-verified.png'});
  await browser.close(); console.log('PASS layout (4 widths), historical edit/date/category/persistence, tab draft, JSON roundtrip/cancel/invalid selection/recovery/corrupt-store repair');
})().catch(e=>{console.error(e);process.exit(1)});
